datasetsForTnP = [
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/new/CMSSW_8_0_10/src/PhysicsTools/TagAndProbe/crab/crab_projects_elev2/crab_2016_RunB/results/processedLumis.json', 'campaign': 'crab_projects_elev2', 'dataset': 'SingleElectron_2016_RunB', 'file': '/store/group/phys_egamma/tnp/80X/Photons_76Xids/elev2/data//TnPTree_SingleElectron_2016_RunB.root', 'lumi': 5.657, 'nEvts': 228669688},
{'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_13_patch1/src/PhysicsTools/TagAndProbe/crab/crab_projects_elev2/crab_2016_RunC//results/processedLumis.json', 'campaign': 'crab_projects_elev2', 'dataset': 'SingleElectron_2016_RunC', 'file': '/store/group/phys_egamma/tnp/80X/Photons_76Xids/elev2/data//TnPTree_SingleElectron_2016_RunC.root', 'lumi': 1.761, 'nEvts': 63419101},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/new/CMSSW_8_0_10/src/PhysicsTools/TagAndProbe/crab/crab_projects_elev2/crab_DYToLL_madgraph/results/processedLumis.json', 'campaign': 'crab_projects_elev2', 'dataset': 'DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8', 'file': '/store/group/phys_egamma/tnp/80X/Photons_76Xids/elev2/mc//TnPTree_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root', 'lumi': -1, 'nEvts': 36311064},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/new/CMSSW_8_0_10/src/PhysicsTools/TagAndProbe/crab/crab_projects_elev2/crab_DYToLL_mcAtNLO//processedLumis.json', 'campaign': 'crab_projects_elev2', 'dataset': 'DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8', 'file': '/store/group/phys_egamma/tnp/80X/Photons_76Xids/elev2/mc//TnPTree_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8.root', 'lumi': -1, 'nEvts': 28696958},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/new/CMSSW_8_0_10/src/PhysicsTools/TagAndProbe/crab/crab_projects_elev2/crab_WJets_madgraph//results/processedLumis.json', 'campaign': 'crab_projects_elev2', 'dataset': 'WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8', 'file': '/store/group/phys_egamma/tnp/80X/Photons_76Xids/elev2/mc//TnPTree_WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root', 'lumi': -1, 'nEvts': 24908024},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/new/CMSSW_8_0_10/src/PhysicsTools/TagAndProbe/crab/crab_projects_phov2/crab_2016_RunB//results/processedLumis.json', 'campaign': 'crab_projects_phov2', 'dataset': 'SingleElectron', 'file': '/store/group/phys_egamma/tnp/80X/Photons_76Xids/phov2/data//TnPTree_SingleElectron.root', 'lumi': 5.848, 'nEvts': 236203597},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/new/CMSSW_8_0_10/src/PhysicsTools/TagAndProbe/crab/crab_projects_phov2/crab_DYToLL_madgraph//results/processedLumis.json', 'campaign': 'crab_projects_phov2', 'dataset': 'DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8', 'file': '/store/group/phys_egamma/tnp/80X/Photons_76Xids/phov2/mc//TnPTree_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root', 'lumi': -1, 'nEvts': 41253879},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/new/CMSSW_8_0_10/src/PhysicsTools/TagAndProbe/crab/crab_projects_phov2/crab_DYToLL_mcAtNLO//results/processedLumis.json', 'campaign': 'crab_projects_phov2', 'dataset': 'DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8', 'file': '/store/group/phys_egamma/tnp/80X/Photons_76Xids/phov2/mc//TnPTree_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8.root', 'lumi': -1, 'nEvts': 28696958},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/new/CMSSW_8_0_10/src/PhysicsTools/TagAndProbe/crab/crab_projects_RECOv3/crab_2016_RunB//results/processedLumis.json', 'campaign': 'crab_projects_RECOv3', 'dataset': 'SingleElectron_2016_RunB', 'file': '/store/group/phys_egamma/tnp/80X/RecoSF/RECOv3/data//TnPTree_SingleElectron_2016_RunB.root', 'lumi': 5.401, 'nEvts': 211415403},
{'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_13_patch1/src/PhysicsTools/TagAndProbe/crab/crab_projects_RECOv3/crab_2016_RunC//results/processedLumis.json', 'campaign': 'crab_projects_RECOv3', 'dataset': 'SingleElectron_2016_RunC', 'file': '/store/group/phys_egamma/tnp/80X/RecoSF/RECOv3/data//TnPTree_SingleElectron_2016_RunC.root', 'lumi': 1.730, 'nEvts': 62332526},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/new/CMSSW_8_0_10/src/PhysicsTools/TagAndProbe/crab/crab_projects_RECOv3/crab_DYToLL_madgraph//results/processedLumis.json', 'campaign': 'crab_projects_RECOv3', 'dataset': 'DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8', 'file': '/store/group/phys_egamma/tnp/80X/RecoSF/RECOv3/mc//TnPTree_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root', 'lumi': -1, 'nEvts': 49877138},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/new/CMSSW_8_0_10/src/PhysicsTools/TagAndProbe/crab/crab_projects_RECOv3/crab_DYToLL_mcAtNLO//results/processedLumis.json', 'campaign': 'crab_projects_RECOv3', 'dataset': 'DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8', 'file': '/store/group/phys_egamma/tnp/80X/RecoSF/RECOv3/mc//TnPTree_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8.root', 'lumi': -1, 'nEvts': 28328619}
    ]
