datasetsForTnP = [
    {'lumiProcessedFile': None, 'campaign': 'crab_project_Moriond17_v1', 'dataset': 'DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_DYToLL_madgraph_Spring16_reHLT', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/Moriond17_v1/mc//TnPTree_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_DYToLL_madgraph_Spring16_reHLT.root', 'lumi': -1, 'nEvts': -1},
    {'lumiProcessedFile': None, 'campaign': 'crab_project_Moriond17_v1', 'dataset': 'SingleElectron_2016rereco_RunB', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/Moriond17_v1/data//TnPTree_SingleElectron_2016rereco_RunB.root', 'lumi': 5.767, 'nEvts': -1},
    {'lumiProcessedFile': None, 'campaign': 'crab_project_Moriond17_v1', 'dataset': 'SingleElectron_2016rereco_RunC', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/Moriond17_v1/data//TnPTree_SingleElectron_2016rereco_RunC.root', 'lumi': 2.646, 'nEvts': -1},    
    {'lumiProcessedFile': None, 'campaign': 'crab_project_Moriond17_v1', 'dataset': 'SingleElectron_2016rereco_RunD', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/Moriond17_v1/data//TnPTree_SingleElectron_2016rereco_RunD.root', 'lumi': 4.353, 'nEvts': -1},
    {'lumiProcessedFile': None, 'campaign': 'crab_project_Moriond17_v1', 'dataset': 'SingleElectron_2016rereco_RunE', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/Moriond17_v1/data//TnPTree_SingleElectron_2016rereco_RunE.root', 'lumi': 3.985, 'nEvts': -1},
    {'lumiProcessedFile': None, 'campaign': 'crab_project_Moriond17_v1', 'dataset': 'SingleElectron_2016rereco_RunF', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/Moriond17_v1/data//TnPTree_SingleElectron_2016rereco_RunF.root', 'lumi': 3.160, 'nEvts': -1},
    {'lumiProcessedFile': None, 'campaign': 'crab_project_Moriond17_v1', 'dataset': 'SingleElectron_2016rereco_RunG', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/Moriond17_v1/data//TnPTree_SingleElectron_2016rereco_RunG.root', 'lumi': 7.539, 'nEvts': -1},
    {'lumiProcessedFile': None, 'campaign': 'crab_project_Moriond17_v1', 'dataset': 'SingleElectron_2016prompt_RunH', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/Moriond17_v1/data//TnPTree_SingleElectron_2016prompt_RunH.root', 'lumi': 8.762, 'nEvts': -1},

    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20/src/PhysicsTools/TagAndProbe/crab/crab_projects_RECOSFs_2016/crab_DYToLL_madgraph_Winter2017//results/processedLumis.json', 'campaign': 'crab_projects_RECOSFs_2016', 'dataset': 'DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_DYToLL_madgraph_Winter2017', 'file': '/store/group/phys_egamma/tnp/80X/RecoSF/RECOSFs_2016/mc//TnPTree_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_DYToLL_madgraph_Winter2017.root', 'lumi': -1, 'nEvts': 49748967},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20_vRECO/src/PhysicsTools/TagAndProbe/crab/crab_projects_RECOSFs_2016/crab_2016rereco_RunB//results/processedLumis.json', 'campaign': 'crab_projects_RECOSFs_2016', 'dataset': 'SingleElectron_2016rereco_RunB', 'file': '/store/group/phys_egamma/tnp/80X/RecoSF/RECOSFs_2016/data//TnPTree_SingleElectron_2016rereco_RunB.root', 'lumi': 5.899, 'nEvts': 238592033},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20/src/PhysicsTools/TagAndProbe/crab/crab_projects_RECOSFs_2016/crab_2016rereco_RunC//results/processedLumis.json', 'campaign': 'crab_projects_RECOSFs_2016', 'dataset': 'SingleElectron_2016rereco_RunC', 'file': '/store/group/phys_egamma/tnp/80X/RecoSF/RECOSFs_2016/data//TnPTree_SingleElectron_2016rereco_RunC.root', 'lumi': 2.646, 'nEvts': 93326652},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20/src/PhysicsTools/TagAndProbe/crab/crab_projects_RECOSFs_2016/crab_2016rereco_RunD//results/processedLumis.json', 'campaign': 'crab_projects_RECOSFs_2016', 'dataset': 'SingleElectron_2016rereco_RunD', 'file': '/store/group/phys_egamma/tnp/80X/RecoSF/RECOSFs_2016/data//TnPTree_SingleElectron_2016rereco_RunD.root', 'lumi': 4.353, 'nEvts': 146480008},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20_vRECO/src/PhysicsTools/TagAndProbe/crab/crab_projects_RECOSFs_2016/crab_2016rereco_RunE//results/processedLumis.json', 'campaign': 'crab_projects_RECOSFs_2016', 'dataset': 'SingleElectron_2016rereco_RunE', 'file': '/store/group/phys_egamma/tnp/80X/RecoSF/RECOSFs_2016/data//TnPTree_SingleElectron_2016rereco_RunE.root', 'lumi': 4.050, 'nEvts': 113169852},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20/src/PhysicsTools/TagAndProbe/crab/crab_projects_RECOSFs_2016/crab_2016rereco_RunF//results/processedLumis.json', 'campaign': 'crab_projects_RECOSFs_2016', 'dataset': 'SingleElectron_2016rereco_RunF', 'file': '/store/group/phys_egamma/tnp/80X/RecoSF/RECOSFs_2016/data//TnPTree_SingleElectron_2016rereco_RunF.root', 'lumi': 3.160, 'nEvts': 70143321},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20_vRECO/src/PhysicsTools/TagAndProbe/crab/crab_projects_RECOSFs_2016/crab_2016rereco_RunG//results/processedLumis.json', 'campaign': 'crab_projects_RECOSFs_2016', 'dataset': 'SingleElectron_2016rereco_RunG', 'file': '/store/group/phys_egamma/tnp/80X/RecoSF/RECOSFs_2016/data//TnPTree_SingleElectron_2016rereco_RunG.root', 'lumi': 7.391, 'nEvts': 148781520},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20_vRECO/src/PhysicsTools/TagAndProbe/crab/crab_projects_RECOSFs_2016/crab_2016prompt_RunHv2//results/processedLumis.json', 'campaign': 'crab_projects_RECOSFs_2016', 'dataset': 'SingleElectron_2016prompt_RunH', 'file': '/store/group/phys_egamma/tnp/80X/RecoSF/RECOSFs_2016/data//TnPTree_SingleElectron_2016prompt_RunH.root', 'lumi': 8.762, 'nEvts': 123900510},


    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20/src/PhysicsTools/TagAndProbe/crab/crab_projects_v2/crab_2016rereco_RunB//results/processedLumis.json', 'campaign': 'crab_projects_v2', 'dataset': 'SingleElectron_2016rereco_RunB', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/v2/data//TnPTree_SingleElectron_2016rereco_RunB.root', 'lumi': 5.349, 'nEvts': 235522176},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20/src/PhysicsTools/TagAndProbe/crab/crab_projects_v2/crab_2016rereco_RunC//results/processedLumis.json', 'campaign': 'crab_projects_v2', 'dataset': 'SingleElectron_2016rereco_RunC', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/v2/data//TnPTree_SingleElectron_2016rereco_RunC.root', 'lumi': 2.363, 'nEvts':  92067646},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20/src/PhysicsTools/TagAndProbe/crab/crab_projects_v2/crab_2016rereco_RunD//results/processedLumis.json', 'campaign': 'crab_projects_v2', 'dataset': 'SingleElectron_2016rereco_RunD', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/v2/data//TnPTree_SingleElectron_2016rereco_RunD.root', 'lumi': 4.256, 'nEvts': 146495223},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20/src/PhysicsTools/TagAndProbe/crab/crab_projects_v2/crab_2016rereco_RunE//results/processedLumis.json', 'campaign': 'crab_projects_v2', 'dataset': 'SingleElectron_2016rereco_RunE', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/v2/data//TnPTree_SingleElectron_2016rereco_RunE.root', 'lumi': 3.981, 'nEvts': 111208237},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20/src/PhysicsTools/TagAndProbe/crab/crab_projects_v2/crab_2016rereco_RunF//results/processedLumis.json', 'campaign': 'crab_projects_v2', 'dataset': 'SingleElectron_2016rereco_RunF', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/v2/data//TnPTree_SingleElectron_2016rereco_RunF.root', 'lumi': 3.105, 'nEvts':  70143321},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20/src/PhysicsTools/TagAndProbe/crab/crab_projects_v2/crab_2016rereco_RunG//results/processedLumis.json', 'campaign': 'crab_projects_v2', 'dataset': 'SingleElectron_2016rereco_RunG', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/v2/data//TnPTree_SingleElectron_2016rereco_RunG.root', 'lumi': 7.544, 'nEvts': 152098617},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20/src/PhysicsTools/TagAndProbe/crab/crab_projects_v2/crab_2016prompt_RunH//results/processedLumis.json', 'campaign': 'crab_projects_v2', 'dataset': 'SingleElectron_2016prompt_RunH', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/v2/data//TnPTree_SingleElectron_2016prompt_RunH.root', 'lumi': 6.105, 'nEvts': 89863172},

    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20/src/PhysicsTools/TagAndProbe/crab/crab_projects_v1/crab_DYToLL_madgraph//results/processedLumis.json', 'campaign': 'crab_projects_v1', 'dataset': 'DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/v1/mc//TnPTree_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_DYToLL_madgraph.root', 'lumi': -1, 'nEvts': 33584160},

    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20/src/PhysicsTools/TagAndProbe/crab/crab_projects_v2/crab_2016prompt_RunB//results/processedLumis.json', 'campaign': 'crab_projects_v2', 'dataset': 'SingleElectron_2016prompt_RunB', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/v2/data//TnPTree_SingleElectron_2016prompt_RunB.root', 'lumi': -1, 'nEvts': 7384544},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20/src/PhysicsTools/TagAndProbe/crab/crab_projects_v2/crab_2016prompt_RunC//results/processedLumis.json', 'campaign': 'crab_projects_v2', 'dataset': 'SingleElectron_2016prompt_RunC', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/v2/data//TnPTree_SingleElectron_2016prompt_RunC.root', 'lumi': -1, 'nEvts': 79103372},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20/src/PhysicsTools/TagAndProbe/crab/crab_projects_v2/crab_2016prompt_RunD//results/processedLumis.json', 'campaign': 'crab_projects_v2', 'dataset': 'SingleElectron_2016prompt_RunD', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/v2/data//TnPTree_SingleElectron_2016prompt_RunD.root', 'lumi': -1, 'nEvts': 124968333},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20/src/PhysicsTools/TagAndProbe/crab/crab_projects_v2/crab_2016prompt_RunF//results/processedLumis.json', 'campaign': 'crab_projects_v2', 'dataset': 'SingleElectron_2016prompt_RunF', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/v2/data//TnPTree_SingleElectron_2016prompt_RunF.root', 'lumi': -1, 'nEvts': 64744869},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20/src/PhysicsTools/TagAndProbe/crab/crab_projects_v2/crab_2016prompt_RunG//results/processedLumis.json', 'campaign': 'crab_projects_v2', 'dataset': 'SingleElectron_2016prompt_RunG', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/v2/data//TnPTree_SingleElectron_2016prompt_RunG.root', 'lumi': -1, 'nEvts': 138296792},

    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20/src/PhysicsTools/TagAndProbe/crab/crab_projects_RECOSFs_2016/crab_DYToLL_madgraph//results/processedLumis.json', 'campaign': 'crab_projects_RECOSFs_2016', 'dataset': 'DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_DYToLL_madgraph', 'file': '/store/group/phys_egamma/tnp/80X/RecoSF/RECOSFs_2016/mc//TnPTree_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_DYToLL_madgraph.root', 'lumi': -1, 'nEvts': 44983870},
    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20/src/PhysicsTools/TagAndProbe/crab/crab_projects_RECOSFs_2016/crab_2016rereco_RunB//results/processedLumis.json', 'campaign': 'crab_projects_RECOSFs_2016', 'dataset': 'SingleElectron_2016rereco_RunB', 'file': '/store/group/phys_egamma/tnp/80X/RecoSF/RECOSFs_2016/data//TnPTree_SingleElectron_2016rereco_RunB.root', 'lumi': -1, 'nEvts': 116256313},
    
#    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20/src/PhysicsTools/TagAndProbe/crab/crab_projects_v1/crab_2016rereco_RunB//results/processedLumis.json', 'campaign': 'crab_projects_v1', 'dataset': 'SingleElectron_2016rereco_RunB', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/v1/data//TnPTree_SingleElectron_2016rereco_RunB.root', 'lumi': 5.364, 'nEvts': 236233675},
#    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20/src/PhysicsTools/TagAndProbe/crab/crab_projects_v1/crab_2016rereco_RunC//results/processedLumis.json', 'campaign': 'crab_projects_v1', 'dataset': 'SingleElectron_2016rereco_RunC', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/v1/data//TnPTree_SingleElectron_2016rereco_RunC.root', 'lumi': 1.810, 'nEvts':  70759545},
#    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20/src/PhysicsTools/TagAndProbe/crab/crab_projects_v1/crab_2016rereco_RunD//results/processedLumis.json', 'campaign': 'crab_projects_v1', 'dataset': 'SingleElectron_2016rereco_RunD', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/v1/data//TnPTree_SingleElectron_2016rereco_RunD.root', 'lumi': 4.241, 'nEvts': 145990095},
#    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20/src/PhysicsTools/TagAndProbe/crab/crab_projects_v1/crab_2016rereco_RunE//results/processedLumis.json', 'campaign': 'crab_projects_v1', 'dataset': 'SingleElectron_2016rereco_RunE', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/v1/data//TnPTree_SingleElectron_2016rereco_RunE.root', 'lumi': 4.054, 'nEvts': 113169852},
#    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20/src/PhysicsTools/TagAndProbe/crab/crab_projects_v1/crab_2016rereco_RunF//results/processedLumis.json', 'campaign': 'crab_projects_v1', 'dataset': 'SingleElectron_2016rereco_RunF', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/v1/data//TnPTree_SingleElectron_2016rereco_RunF.root', 'lumi': 3.085, 'nEvts':  69673589},
#    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_20/src/PhysicsTools/TagAndProbe/crab/crab_projects_v1/crab_2016rereco_RunG//results/processedLumis.json', 'campaign': 'crab_projects_v1', 'dataset': 'SingleElectron_2016rereco_RunG', 'file': '/store/group/phys_egamma/tnp/80X/PhoEleIDs/v1/data//TnPTree_SingleElectron_2016rereco_RunG.root', 'lumi': 7.521, 'nEvts': 151654044},

#    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/new/CMSSW_8_0_10/src/PhysicsTools/TagAndProbe/crab/crab_projects_elev2/crab_2016_RunB/results/processedLumis.json', 'campaign': 'crab_projects_elev2', 'dataset': 'SingleElectron_2016_RunB', 'file': '/store/group/phys_egamma/tnp/80X/Photons_76Xids/elev2/data//TnPTree_SingleElectron_2016_RunB.root', 'lumi': 5.657, 'nEvts': 228669688},
#    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_13_patch1/src/PhysicsTools/TagAndProbe/crab/crab_projects_elev2/crab_2016_RunC//results/processedLumis.json', 'campaign': 'crab_projects_elev2', 'dataset': 'SingleElectron_2016_RunC', 'file': '/store/group/phys_egamma/tnp/80X/Photons_76Xids/elev2/data//TnPTree_SingleElectron_2016_RunC.root', 'lumi': 1.761, 'nEvts': 63419101},
#    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/new/CMSSW_8_0_10/src/PhysicsTools/TagAndProbe/crab/crab_projects_elev2/crab_DYToLL_madgraph/results/processedLumis.json', 'campaign': 'crab_projects_elev2', 'dataset': 'DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8', 'file': '/store/group/phys_egamma/tnp/80X/Photons_76Xids/elev2/mc//TnPTree_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root', 'lumi': -1, 'nEvts': 36311064},
#    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/new/CMSSW_8_0_10/src/PhysicsTools/TagAndProbe/crab/crab_projects_elev2/crab_DYToLL_mcAtNLO//processedLumis.json', 'campaign': 'crab_projects_elev2', 'dataset': 'DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8', 'file': '/store/group/phys_egamma/tnp/80X/Photons_76Xids/elev2/mc//TnPTree_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8.root', 'lumi': -1, 'nEvts': 28696958},
#    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/new/CMSSW_8_0_10/src/PhysicsTools/TagAndProbe/crab/crab_projects_elev2/crab_WJets_madgraph//results/processedLumis.json', 'campaign': 'crab_projects_elev2', 'dataset': 'WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8', 'file': '/store/group/phys_egamma/tnp/80X/Photons_76Xids/elev2/mc//TnPTree_WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root', 'lumi': -1, 'nEvts': 24908024},
#    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/new/CMSSW_8_0_10/src/PhysicsTools/TagAndProbe/crab/crab_projects_phov2/crab_2016_RunB//results/processedLumis.json', 'campaign': 'crab_projects_phov2', 'dataset': 'SingleElectron', 'file': '/store/group/phys_egamma/tnp/80X/Photons_76Xids/phov2/data//TnPTree_SingleElectron.root', 'lumi': 5.848, 'nEvts': 236203597},
#    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/new/CMSSW_8_0_10/src/PhysicsTools/TagAndProbe/crab/crab_projects_phov2/crab_DYToLL_madgraph//results/processedLumis.json', 'campaign': 'crab_projects_phov2', 'dataset': 'DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8', 'file': '/store/group/phys_egamma/tnp/80X/Photons_76Xids/phov2/mc//TnPTree_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root', 'lumi': -1, 'nEvts': 41253879},
#    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/new/CMSSW_8_0_10/src/PhysicsTools/TagAndProbe/crab/crab_projects_phov2/crab_DYToLL_mcAtNLO//results/processedLumis.json', 'campaign': 'crab_projects_phov2', 'dataset': 'DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8', 'file': '/store/group/phys_egamma/tnp/80X/Photons_76Xids/phov2/mc//TnPTree_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8.root', 'lumi': -1, 'nEvts': 28696958},
#    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/new/CMSSW_8_0_10/src/PhysicsTools/TagAndProbe/crab/crab_projects_RECOv3/crab_2016_RunB//results/processedLumis.json', 'campaign': 'crab_projects_RECOv3', 'dataset': 'SingleElectron_2016_RunB', 'file': '/store/group/phys_egamma/tnp/80X/RecoSF/RECOv3/data//TnPTree_SingleElectron_2016_RunB.root', 'lumi': 5.401, 'nEvts': 211415403},
#    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/CMSSW_8_0_13_patch1/src/PhysicsTools/TagAndProbe/crab/crab_projects_RECOv3/crab_2016_RunC//results/processedLumis.json', 'campaign': 'crab_projects_RECOv3', 'dataset': 'SingleElectron_2016_RunC', 'file': '/store/group/phys_egamma/tnp/80X/RecoSF/RECOv3/data//TnPTree_SingleElectron_2016_RunC.root', 'lumi': 1.730, 'nEvts': 62332526},
#    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/new/CMSSW_8_0_10/src/PhysicsTools/TagAndProbe/crab/crab_projects_RECOv3/crab_DYToLL_madgraph//results/processedLumis.json', 'campaign': 'crab_projects_RECOv3', 'dataset': 'DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8', 'file': '/store/group/phys_egamma/tnp/80X/RecoSF/RECOv3/mc//TnPTree_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root', 'lumi': -1, 'nEvts': 49877138},
#    {'lumiProcessedFile': '/afs/cern.ch/work/f/fcouderc/public/EGamma/TnP/new/CMSSW_8_0_10/src/PhysicsTools/TagAndProbe/crab/crab_projects_RECOv3/crab_DYToLL_mcAtNLO//results/processedLumis.json', 'campaign': 'crab_projects_RECOv3', 'dataset': 'DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8', 'file': '/store/group/phys_egamma/tnp/80X/RecoSF/RECOv3/mc//TnPTree_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8.root', 'lumi': -1, 'nEvts': 28328619}
    ]
